// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.0--rc2
// source: proto/mira_ida_access_service.proto

package mirapb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MiraIdaAccess_GetPrivateDBConnInfo_FullMethodName        = "/mira.MiraIdaAccess/GetPrivateDBConnInfo"
	MiraIdaAccess_GetPrivateAssetInfoByEnName_FullMethodName = "/mira.MiraIdaAccess/GetPrivateAssetInfoByEnName"
	MiraIdaAccess_GetPrivateAssetList_FullMethodName         = "/mira.MiraIdaAccess/GetPrivateAssetList"
	MiraIdaAccess_GetPrivateAssetInfo_FullMethodName         = "/mira.MiraIdaAccess/GetPrivateAssetInfo"
	MiraIdaAccess_CreateDataSource_FullMethodName            = "/mira.MiraIdaAccess/CreateDataSource"
	MiraIdaAccess_CreateAsset_FullMethodName                 = "/mira.MiraIdaAccess/CreateAsset"
	MiraIdaAccess_UpdateAsset_FullMethodName                 = "/mira.MiraIdaAccess/UpdateAsset"
	MiraIdaAccess_DeleteAsset_FullMethodName                 = "/mira.MiraIdaAccess/DeleteAsset"
)

// MiraIdaAccessClient is the client API for MiraIdaAccess service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IDA Access Service 定义
type MiraIdaAccessClient interface {
	// 获取包含隐私信息的数据源连接信息接口
	GetPrivateDBConnInfo(ctx context.Context, in *GetPrivateDBConnInfoRequest, opts ...grpc.CallOption) (*GetPrivateDBConnInfoResponse, error)
	// 通过资产英文名称获取资产详情
	GetPrivateAssetInfoByEnName(ctx context.Context, in *GetPrivateAssetInfoByEnNameRequest, opts ...grpc.CallOption) (*GetPrivateAssetInfoByEnNameResponse, error)
	// 获取资产列表
	GetPrivateAssetList(ctx context.Context, in *GetPrivateAssetListRequest, opts ...grpc.CallOption) (*GetPrivateAssetListResponse, error)
	// 通过资产ID获取资产详情
	GetPrivateAssetInfo(ctx context.Context, in *GetPrivateAssetInfoRequest, opts ...grpc.CallOption) (*GetPrivateAssetInfoResponse, error)
	// 创建数据源
	CreateDataSource(ctx context.Context, in *CreateDataSourceRequest, opts ...grpc.CallOption) (*CreateDataSourceResponse, error)
	// 创建资产
	CreateAsset(ctx context.Context, in *CreateAssetRequest, opts ...grpc.CallOption) (*CreateAssetResponse, error)
	// 更新资产
	UpdateAsset(ctx context.Context, in *UpdateAssetRequest, opts ...grpc.CallOption) (*UpdateAssetResponse, error)
	// 删除资产
	DeleteAsset(ctx context.Context, in *DeleteAssetRequest, opts ...grpc.CallOption) (*DeleteAssetResponse, error)
}

type miraIdaAccessClient struct {
	cc grpc.ClientConnInterface
}

func NewMiraIdaAccessClient(cc grpc.ClientConnInterface) MiraIdaAccessClient {
	return &miraIdaAccessClient{cc}
}

func (c *miraIdaAccessClient) GetPrivateDBConnInfo(ctx context.Context, in *GetPrivateDBConnInfoRequest, opts ...grpc.CallOption) (*GetPrivateDBConnInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPrivateDBConnInfoResponse)
	err := c.cc.Invoke(ctx, MiraIdaAccess_GetPrivateDBConnInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *miraIdaAccessClient) GetPrivateAssetInfoByEnName(ctx context.Context, in *GetPrivateAssetInfoByEnNameRequest, opts ...grpc.CallOption) (*GetPrivateAssetInfoByEnNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPrivateAssetInfoByEnNameResponse)
	err := c.cc.Invoke(ctx, MiraIdaAccess_GetPrivateAssetInfoByEnName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *miraIdaAccessClient) GetPrivateAssetList(ctx context.Context, in *GetPrivateAssetListRequest, opts ...grpc.CallOption) (*GetPrivateAssetListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPrivateAssetListResponse)
	err := c.cc.Invoke(ctx, MiraIdaAccess_GetPrivateAssetList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *miraIdaAccessClient) GetPrivateAssetInfo(ctx context.Context, in *GetPrivateAssetInfoRequest, opts ...grpc.CallOption) (*GetPrivateAssetInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPrivateAssetInfoResponse)
	err := c.cc.Invoke(ctx, MiraIdaAccess_GetPrivateAssetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *miraIdaAccessClient) CreateDataSource(ctx context.Context, in *CreateDataSourceRequest, opts ...grpc.CallOption) (*CreateDataSourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDataSourceResponse)
	err := c.cc.Invoke(ctx, MiraIdaAccess_CreateDataSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *miraIdaAccessClient) CreateAsset(ctx context.Context, in *CreateAssetRequest, opts ...grpc.CallOption) (*CreateAssetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAssetResponse)
	err := c.cc.Invoke(ctx, MiraIdaAccess_CreateAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *miraIdaAccessClient) UpdateAsset(ctx context.Context, in *UpdateAssetRequest, opts ...grpc.CallOption) (*UpdateAssetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAssetResponse)
	err := c.cc.Invoke(ctx, MiraIdaAccess_UpdateAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *miraIdaAccessClient) DeleteAsset(ctx context.Context, in *DeleteAssetRequest, opts ...grpc.CallOption) (*DeleteAssetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAssetResponse)
	err := c.cc.Invoke(ctx, MiraIdaAccess_DeleteAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MiraIdaAccessServer is the server API for MiraIdaAccess service.
// All implementations must embed UnimplementedMiraIdaAccessServer
// for forward compatibility.
//
// IDA Access Service 定义
type MiraIdaAccessServer interface {
	// 获取包含隐私信息的数据源连接信息接口
	GetPrivateDBConnInfo(context.Context, *GetPrivateDBConnInfoRequest) (*GetPrivateDBConnInfoResponse, error)
	// 通过资产英文名称获取资产详情
	GetPrivateAssetInfoByEnName(context.Context, *GetPrivateAssetInfoByEnNameRequest) (*GetPrivateAssetInfoByEnNameResponse, error)
	// 获取资产列表
	GetPrivateAssetList(context.Context, *GetPrivateAssetListRequest) (*GetPrivateAssetListResponse, error)
	// 通过资产ID获取资产详情
	GetPrivateAssetInfo(context.Context, *GetPrivateAssetInfoRequest) (*GetPrivateAssetInfoResponse, error)
	// 创建数据源
	CreateDataSource(context.Context, *CreateDataSourceRequest) (*CreateDataSourceResponse, error)
	// 创建资产
	CreateAsset(context.Context, *CreateAssetRequest) (*CreateAssetResponse, error)
	// 更新资产
	UpdateAsset(context.Context, *UpdateAssetRequest) (*UpdateAssetResponse, error)
	// 删除资产
	DeleteAsset(context.Context, *DeleteAssetRequest) (*DeleteAssetResponse, error)
	mustEmbedUnimplementedMiraIdaAccessServer()
}

// UnimplementedMiraIdaAccessServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMiraIdaAccessServer struct{}

func (UnimplementedMiraIdaAccessServer) GetPrivateDBConnInfo(context.Context, *GetPrivateDBConnInfoRequest) (*GetPrivateDBConnInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPrivateDBConnInfo not implemented")
}
func (UnimplementedMiraIdaAccessServer) GetPrivateAssetInfoByEnName(context.Context, *GetPrivateAssetInfoByEnNameRequest) (*GetPrivateAssetInfoByEnNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPrivateAssetInfoByEnName not implemented")
}
func (UnimplementedMiraIdaAccessServer) GetPrivateAssetList(context.Context, *GetPrivateAssetListRequest) (*GetPrivateAssetListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPrivateAssetList not implemented")
}
func (UnimplementedMiraIdaAccessServer) GetPrivateAssetInfo(context.Context, *GetPrivateAssetInfoRequest) (*GetPrivateAssetInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPrivateAssetInfo not implemented")
}
func (UnimplementedMiraIdaAccessServer) CreateDataSource(context.Context, *CreateDataSourceRequest) (*CreateDataSourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDataSource not implemented")
}
func (UnimplementedMiraIdaAccessServer) CreateAsset(context.Context, *CreateAssetRequest) (*CreateAssetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAsset not implemented")
}
func (UnimplementedMiraIdaAccessServer) UpdateAsset(context.Context, *UpdateAssetRequest) (*UpdateAssetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAsset not implemented")
}
func (UnimplementedMiraIdaAccessServer) DeleteAsset(context.Context, *DeleteAssetRequest) (*DeleteAssetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAsset not implemented")
}
func (UnimplementedMiraIdaAccessServer) mustEmbedUnimplementedMiraIdaAccessServer() {}
func (UnimplementedMiraIdaAccessServer) testEmbeddedByValue()                       {}

// UnsafeMiraIdaAccessServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MiraIdaAccessServer will
// result in compilation errors.
type UnsafeMiraIdaAccessServer interface {
	mustEmbedUnimplementedMiraIdaAccessServer()
}

func RegisterMiraIdaAccessServer(s grpc.ServiceRegistrar, srv MiraIdaAccessServer) {
	// If the following call pancis, it indicates UnimplementedMiraIdaAccessServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MiraIdaAccess_ServiceDesc, srv)
}

func _MiraIdaAccess_GetPrivateDBConnInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPrivateDBConnInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiraIdaAccessServer).GetPrivateDBConnInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiraIdaAccess_GetPrivateDBConnInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiraIdaAccessServer).GetPrivateDBConnInfo(ctx, req.(*GetPrivateDBConnInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MiraIdaAccess_GetPrivateAssetInfoByEnName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPrivateAssetInfoByEnNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiraIdaAccessServer).GetPrivateAssetInfoByEnName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiraIdaAccess_GetPrivateAssetInfoByEnName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiraIdaAccessServer).GetPrivateAssetInfoByEnName(ctx, req.(*GetPrivateAssetInfoByEnNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MiraIdaAccess_GetPrivateAssetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPrivateAssetListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiraIdaAccessServer).GetPrivateAssetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiraIdaAccess_GetPrivateAssetList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiraIdaAccessServer).GetPrivateAssetList(ctx, req.(*GetPrivateAssetListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MiraIdaAccess_GetPrivateAssetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPrivateAssetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiraIdaAccessServer).GetPrivateAssetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiraIdaAccess_GetPrivateAssetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiraIdaAccessServer).GetPrivateAssetInfo(ctx, req.(*GetPrivateAssetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MiraIdaAccess_CreateDataSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDataSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiraIdaAccessServer).CreateDataSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiraIdaAccess_CreateDataSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiraIdaAccessServer).CreateDataSource(ctx, req.(*CreateDataSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MiraIdaAccess_CreateAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiraIdaAccessServer).CreateAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiraIdaAccess_CreateAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiraIdaAccessServer).CreateAsset(ctx, req.(*CreateAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MiraIdaAccess_UpdateAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiraIdaAccessServer).UpdateAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiraIdaAccess_UpdateAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiraIdaAccessServer).UpdateAsset(ctx, req.(*UpdateAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MiraIdaAccess_DeleteAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiraIdaAccessServer).DeleteAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiraIdaAccess_DeleteAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiraIdaAccessServer).DeleteAsset(ctx, req.(*DeleteAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MiraIdaAccess_ServiceDesc is the grpc.ServiceDesc for MiraIdaAccess service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MiraIdaAccess_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mira.MiraIdaAccess",
	HandlerType: (*MiraIdaAccessServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPrivateDBConnInfo",
			Handler:    _MiraIdaAccess_GetPrivateDBConnInfo_Handler,
		},
		{
			MethodName: "GetPrivateAssetInfoByEnName",
			Handler:    _MiraIdaAccess_GetPrivateAssetInfoByEnName_Handler,
		},
		{
			MethodName: "GetPrivateAssetList",
			Handler:    _MiraIdaAccess_GetPrivateAssetList_Handler,
		},
		{
			MethodName: "GetPrivateAssetInfo",
			Handler:    _MiraIdaAccess_GetPrivateAssetInfo_Handler,
		},
		{
			MethodName: "CreateDataSource",
			Handler:    _MiraIdaAccess_CreateDataSource_Handler,
		},
		{
			MethodName: "CreateAsset",
			Handler:    _MiraIdaAccess_CreateAsset_Handler,
		},
		{
			MethodName: "UpdateAsset",
			Handler:    _MiraIdaAccess_UpdateAsset_Handler,
		},
		{
			MethodName: "DeleteAsset",
			Handler:    _MiraIdaAccess_DeleteAsset_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mira_ida_access_service.proto",
}
